### ISSUE TITLE
How should I get the Quantitative results for the previous model in rows 1-3 of TABLE 1

### ISSUE THREAD

**Issue by Full-Adder** [jc043/CPL#2]
Hello, thank you for making such a wonderful paper. As the title suggests, it is not clear to me how the Quantitative results of the previous work were trained to obtain them, was it through continuous training or general joint training? That is in Table 1. Quantitative results of continual predictive learning on the RoboNet benchmark in both action-conditioned and action-free setups.
![image](https://user-images.githubusercontent.com/49706419/231726093-08d42a42-1c6a-4dd8-9278-aebb5625f89c.png)

**Comment by jc043** [comment]
Sorry for ignoring the issue! The results of previous works are trained through continuous learning in the same setting as our CPL-full result.
