### ISSUE TITLE
关于对比实验的代码

### ISSUE THREAD

**Issue by Full-Adder** [jc043/CPL#3]
您好，感谢您精彩的工作，在对比实验中，我有下面的问题向您请教：
1.  CPL-base + Lwf为什么没有做实验对比呀？
1. 关于PredRNN + LwF、 PredRNN + EWC、 CPL-base + EWC 的代码可以提供一下吗？

**Comment by Full-Adder** [comment]
RoboNet Benchmark的实验代码在未来会公开吗？

**Comment by jc043** [comment]
感谢您对我们工作的关注！没有做CPL-base+Lwf主要是出于实验中发现Lwf在PredRNN上的效果比较差，基本没有什么正向作用，因此就没有继续在CPL-base上实验。另外关于Baseline和RoboNet的代码，由于我已经从实验室毕业，因此抱歉可能没办法提供了。
